#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sourcetree()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} "$@"
   log_fluff "####################################" >&2

   (
      set +e
      MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} libexec-dir`"

      # MULLE_SOURCETREE_FLAGS are picked up by mulle-sourcetree
      . "${MULLE_SOURCETREE}" --no-auto-shell "$@"
   )
}

#
# repository has no .mulle in 1.0.0
# repository has a .mulle-sourcetree in 2.0.0
# repository has no .mulle in 3.0.0
#
_setup_demo_repo_a()
{
   local reporoot="$1"

   exekutor git init

   redirect_exekutor VERSION echo "1.0.0"
   exekutor git add VERSION
   exekutor git commit -m "a: initial version 1.0.0 (tagged)"
   exekutor git tag "1.0.0"

   redirect_exekutor VERSION echo "2.0.0"
   run_mulle_sourcetree -N add --nodetype git "file://${reporoot}/b"
   [ -f .mulle/etc/sourcetree/config ] || internal_fail "fail add $(PWD)"
   exekutor git add VERSION .mulle
   exekutor git commit -m "a: version 2.0.0 (tagged)"
   exekutor git tag "2.0.0"
}


_setup_demo_repo_b()
{
   local reporoot="$1"

   exekutor git init

   redirect_exekutor VERSION echo "1.0.0"
   exekutor git add VERSION
   exekutor git commit -m "b: initial version"
}


setup_demo_repos()
{
   (
      set -e
      mkdir_if_missing "$1/a" &&
      exekutor cd "$1/a"      && _setup_demo_repo_a "$1"
      mkdir_if_missing "$1/b" &&
      exekutor cd "$1/b"      && _setup_demo_repo_b "$1"
      set +e
   ) || exit 1
}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   local project

   project="${directory}/project"
   repos="${directory}/repositories"

   setup_demo_repos "${repos}"

   mkdir_if_missing "${project}"

   local number=1

   (
      cd "${project}"

      local a
      local version

      for a in 1.0.0 2.0.0 1.0.0
      do
         if ! run_mulle_sourcetree -N add --nodetype git --tag "${a}" "file://${repos}/a"
         then
           internal_fail "add failed unexpectedly ($PWD)"
         fi

         run_mulle_sourcetree -N  list --output-full

         if ! run_mulle_sourcetree -N --recurse update
         then
            internal_fail "update failed unexpectedly ($PWD)"
         fi

         version="`cat a/VERSION`"
         [ "${a}" != "${VERSION}" ] || internal_fail "Checked out version $VERSION instead of $a"

         case "${a}" in
            1.0.0)
               [ -d "a" ]   || internal_fail "a should exist"
               [ -d "a/b" ] && internal_fail "a/b should not exist"
            ;;

            2.0.0)
               [ -d "a" ]   || internal_fail "a should exist"
               [ -d "a/b" ] || internal_fail "a/b should exist"
            ;;
         esac

         run_mulle_sourcetree -N remove "a"

         log_info "----- #${number} PASSED -----"
         number="$(expr $number + 1)"
      done
   ) || exit 1


   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}


init()
{
   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh"     || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh"       || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-callback.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-sync.sh"     || exit 1
}


init "$@"
main "$@"

