#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


run_mulle_sourcetree()
{
   log_fluff "####################################"
   log_fluff ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} "$@"
}


setup_test()
{
   mkdir a b c d

   ln -s ../a a
   ln -s ../b a/b
   ln -s ../c a/c
   ln -s ../d b/d
   ln -s ../d c/d

   run_mulle_sourcetree -s -d a add b
   run_mulle_sourcetree -s -d a add c
   run_mulle_sourcetree -s -d b add d
   run_mulle_sourcetree -s -d c add d

   mkdir project
   cd project
   run_mulle_sourcetree -s add a
   ln -s ../a a
}


walk_test()
{
   local mode="$1"
   local expect="$2"

   local result

   result="`run_mulle_sourcetree walk ${mode} 'echo "${MULLE_ADDRESS}"' `"
   [ "${expect}" = "${result}" ] || internal_fail "${mode#2} fail: \"${result}\" != \"${expect}\""

   log_verbose "----- #$testno PASSED -----"
   testno=$(( testno + 1))
}


run_test()
{
   local expect
   local testno

   testno=1
   walk_test --flat "a"

   walk_test --pre-order "a
b
d
c
d"

   walk_test --in-order "d
b
d
c
a"


   walk_test --breadth-first "a
b
c
d
d"
}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   directory="`make_tmp_directory`" || exit 1

   cd "${directory}"

   setup_test
   run_test

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh" || exit 1
}


init "$@"
main "$@"

