#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


run_mulle_sourcetree()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} "$@"
   log_fluff "####################################" >&2

   (
      MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} libexec-dir`"

      . "${MULLE_SOURCETREE}" --no-auto-shell ${MULLE_SOURCETREE_FLAGS} "$@"
   )
}


#
#       -> a -> b -> d
#            -> c -> d
#     or
#
#       a
#      / \
#     b   c
#      \ /
#       d
#
setup_test()
{
   mkdir a b c d

   ln -s ../a a
   ln -s ../b a/b
   ln -s ../c a/c
   ln -s ../d b/d
   ln -s ../d c/d

   run_mulle_sourcetree -s -d a add b
   run_mulle_sourcetree -s -d a add c
   run_mulle_sourcetree -s -d b add d
   run_mulle_sourcetree -s -d c add d

   mkdir project
   cd project
   run_mulle_sourcetree -s add a
   ln -s ../a a
}


walk_test()
{
   local mode="$1"
   local expect="$2"

   local result

   result="`run_mulle_sourcetree walk ${mode} 'printf "%s\n" "${NODE_ADDRESS}"' `"
   [ "${expect}" = "${result}" ] || internal_fail "${mode#2} fail: \"${result}\" != \"${expect}\""

   log_verbose "----- #$testno PASSED -----"
   testno=$(( testno + 1))
}


run_test()
{
   local expect
   local testno

   testno=1

###
# flat:
#
#       a 1

   walk_test --flat "a"

###
# in-order:
#
#       a 3 6
#      / \
#   2 b   c 5
#      \ /
#     1 d 4

#   walk_test --in-order "d
#b
#a
#d
#c
#a"

###
# pre-order:
#
#       a 1
#      / \
#   2 b   c 4
#      \ /
#     3 d 5

   walk_test --pre-order "a
b
d
c
d"

###
# pre-order backwards:
#       a 1
#      / \
#   4 b   c 2
#      \ /
#     5 d 3

   walk_test "--pre-order --backwards" "a
c
d
b
d"

###
# post-order:
#
#       a 5
#      / \
#   3 b   c 4
#      \ /
#     1 d 2

   walk_test --post-order "d
d
b
c
a"


###
# post-order backwards:
#
#       a 5
#      / \
#   4 b   c 3
#      \ /
#     2 d 1

   walk_test "--post-order --backwards" "d
d
c
b
a"

###
# breadth-first:
#
#       a 1
#      / \
#   2 b   c 3
#      \ /
#     4 d 5

   walk_test --breadth-first "a
b
c
d
d"


###
# breadth-first backwards:
#
#       a 1
#      / \
#   3 b   c 2
#      \ /
#     5 d 4

   walk_test "--breadth-first --backwards"  "a
c
b
d
d"


}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   cd "${directory}"

   setup_test
   run_test

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh" || exit 1
}


init "$@"
main "$@"

