#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sourcetree()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS:-} "$@"
   log_fluff "####################################" >&2

   (
      set +e
      
      MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} libexec-dir`"

      . "${MULLE_SOURCETREE}" ${MULLE_SOURCETREE_FLAGS:-} "$@"
   )
}


#
# repository has no .mulle in 1.0.0
# repository has a .mulle in 2.0.0
# repository has no .mulle in 3.0.0
#
_setup_demo_repo_a()
{
   local reporoot="$1"

   exekutor git init

   redirect_exekutor VERSION echo "1.0.0"
   exekutor git add VERSION
   exekutor git commit -m "a: initial version"
}


_setup_demo_repo_b()
{
   local reporoot="$1"

   exekutor git init

   redirect_exekutor VERSION echo "1.1.0"
   run_mulle_sourcetree -s add --nodetype git "file://${reporoot}/c"
   exekutor git add VERSION .mulle
   exekutor git commit -m "b: initial version"
}


_setup_demo_repo_c()
{
   local reporoot="$1"

   exekutor git init

   redirect_exekutor VERSION echo "1.0.0"
   exekutor git add VERSION
   exekutor git commit -m "c: initial version"
}


setup_demo_repos()
{
   (
      set -e
      mkdir_if_missing "$1/a" &&
      exekutor cd "$1/a" && _setup_demo_repo_a "$1"
      mkdir_if_missing "$1/b" &&
      exekutor cd "$1/b" && _setup_demo_repo_b "$1"
      mkdir_if_missing "$1/c" &&
      exekutor cd "$1/c" && _setup_demo_repo_c "$1"
      set +e
   ) || exit 1
}

dump()
{
   local project="$1"

   (
      cd "${project}" &&
      for i in .mulle/var/walitza/sourcetree/db/*
      do
         log_verbose "`basename -- "$i" `::"
         cat "$i"
         echo
      done
   )
}


dump_fail()
{
   dump "$@"
   fail "failed"
}

#
#  a -> b
#  a -> c
#  b -> c
#
main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"

   local project

   project="${directory}/project"
   repos="${directory}/repositories"


   log_verbose "------- SETUP-------"
   setup_demo_repos "${repos}"

   log_verbose "------- START-------"

   mkdir_if_missing "${project}"
   cd "${project}" &&
   run_mulle_sourcetree add --nodetype git "file://${repos}/a" &&
   run_mulle_sourcetree add --nodetype git "file://${repos}/b" || fail "failed"

#  run_mulle_sourcetree list &&
   run_mulle_sourcetree --share sync &&
#   dump "${project}" &&
   run_mulle_sourcetree remove b  &&

#   run_mulle_sourcetree list &&
   run_mulle_sourcetree --share sync || dump_fail "${project}"

   [ -d "stash/b" ] && fail "b still there"
   [ -d "stash/c" ] && fail "c still there"

   log_verbose "----- #1 PASSED -----"

   run_mulle_sourcetree add --nodetype git "file://${repos}/b" &&
   run_mulle_sourcetree --share sync &&
#   dump "${project}" &&
   run_mulle_sourcetree remove b  &&
   # c reappears somewhere else
   run_mulle_sourcetree -s add --nodetype git "file://${repos}/c" &&
   run_mulle_sourcetree --share sync || dump_fail "${project}"

   [ -d "stash/b" ] && fail "b still there"
   [ ! -d "stash/c" ] && fail "c not there"

   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"
   cd /
   rmdir_safer "${directory}"
}


init()
{
   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh"     || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh"       || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-callback.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-sync.sh"     || exit 1
}


init "$@"
main "$@"

