#! /usr/bin/env bash
#
#   Copyright (c) 2018 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = 'YES' -o "${MULLE_C_SOURCETREE_UPDATE_TRACE}" = 'YES' ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION="0.19.1"


usage()
{
   cat <<EOF >&2
Usage:
   ${MULLE_USAGE_NAME} [flags]

   Produce _<project>-include.h files and related headers. Also can produce
   #import files for Objective-C.

   This tool reads the contents of the sourcetree and uses the information to
   produce header files.

   Node info used:
      address    : to generate the default include <name>
      marks      : see below
      include    : specifies include name to use, if present

   Marks used:
      dependency : slightly different semantics for default include generation
      require    : fence with \`#if __has_include\`
      import     : use import instead of include as
      public     : takes part in the genereation of the public include file
      os         : to producde #ifndef __APPLE__ and such

Flags:
   --stdout      : Emit to stdout instead
   --import      : Emit import files
   --no-import   : Don't emit import files

Environment:
   MULLE_SOURCETREE_TO_C_INCLUDE_FILE        | Use DISABLE to turn of
   MULLE_SOURCETREE_TO_C_IMPORT_FILE         | file generation. NONE to emit an
   MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE | empty file. - outputs to stdout.
   MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE  | Otherwise the filename.
EOF
   exit 1
}


r_uname_to_cpp()
{
   log_entry "r_uname_to_cpp" "$@"

   local uname="$1"  # the part after only-os or no

   case "${uname}" in
      'darwin')
         RVAL="__APPLE__"
      ;;

      'freebsd')
         RVAL="BSD4_3"  # guess
      ;;

      'mingw'*)
         RVAL="_WIN32"
      ;;

      *)
         RVAL="__${uname}__"
      ;;
   esac
}


r_osexclude_to_cpp_if()
{
   log_entry "r_osexclude_to_cpp_if" "$@"

   local marks="$1"

   local cppvar

   local excludes
   local onlys

   set -o noglob ; IFS=","

   for osexclude in ${marks}
   do
      IFS="${DEFAULT_IFS}"; set +o noglob

      case "${osexclude}" in
         only-os-*)
				r_uname_to_cpp "${osexclude:8}"
            r_concat "${onlys}" "defined( ${RVAL})" " || "
            onlys="${RVAL}"
         ;;

         no-os-*)
				r_uname_to_cpp "${osexclude:6}"
            r_concat "${excludes}" "! defined( ${RVAL})" " && "
            excludes="${RVAL}"
         ;;
      esac
   done
   IFS="${DEFAULT_IFS}"; set +o noglob

   if [ ! -z "${onlys}" ]
   then
      RVAL="# if ${onlys}"
      return
   fi

   if [ ! -z "${excludes}" ]
   then
      RVAL="# if ${excludes}"
      return
   fi

   RVAL=""
}


_emit_c_include()
{
   log_entry "_emit_c_include" "$@"

   local address="$1"
   local header="$2"
   local marks="$3"

   local indent
   local ifstatement
   local include
   local mark

   #
   # so objc can reuse this, make a provision for import with --objc flag
   # but allow #include if the mark no-objc is set
   #
   include="include"
   if [ "${OPTION_IMPORT}" = 'YES' ]
   then
      include="import"

      case ",${marks}," in
         *,no-import,*)
            include="include"
         ;;
      esac
   fi

   echo "// remove with \`mulle-sourcetree mark ${address} no-header\`"
   echo "// rename with \`mulle-sourcetree mark ${address} set include whatever.h\`"

   if [ ! -z "${marks}" ]
   then
   	r_osexclude_to_cpp_if "${marks}"
      ifstatement="${RVAL}"
   fi

   if [ ! -z "${ifstatement}" ]
   then
      printf "%s\n" "${ifstatement}"
      indent=" "
   fi

   # TODO: remove support __has_include for C ? Not all C compilers have
   #       __has_include
   case ",${marks}," in
      *,no-require,*)
         local name

         name="`tr -c 'a-zA-Z0-9' '_' <<< "${address}" | tr a-z A-Z`"

         echo "# ifdef __has_include"
         echo "#  if __has_include(<${header}>)"
         echo "#   ${indent}${include} <${header}>   // ${address}"
         echo "#   define HAVE_LIB_${name%%_}"
         echo "#  endif"
         echo "# endif"
      ;;

      *)
         echo "# ${indent}${include} <${header}>   // ${address}"
      ;;
   esac


   if [ ! -z "${ifstatement}" ]
   then
      echo "# endif"
   fi

   echo
}


emit_c_include_library()
{
   log_entry "emit_c_include_library" "$@"

   local address="$1"
   local marks="$2"
   local header="$3"

   #
   # the default for libraries is old style <name.h> not <name/name.h>
   #
   if [ -z "${header}" ]
   then
      local name

      r_fast_basename "${address%#*}"
      name="${RVAL}"
      header="${name}.h"
   fi

   _emit_c_include "${address}" "${header}" "${marks}"

}


emit_c_include_dependency()
{
   log_entry "emit_c_include_dependency" "$@"

   local address="$1"
   local marks="$2"
   local header="$3"

   #
   # the default for dependencies is <name/name.h>
   #
   if [ -z "${header}" ]
   then
      local name

      r_fast_basename "${address%#*}"
      name="${RVAL}"
      header="${name}/${name}.h"
   fi

   _emit_c_include "${address}" "${header}" "${marks}"
}


emit_c_header()
{
   log_entry "emit_c_header" "$@"

   local marks="$1"

   local filter_marks

   r_comma_concat "header" "${marks}"
   filter_marks="${RVAL}"

   # since the order of the headers is important and needs to be in treeorder
   # we use mulle-sourcetree directly
   local headers

   headers="`exekutor mulle-sourcetree list \
                                       --format "%a;%m;%i={include,,-------}\\n" \
                                       --marks "${filter_marks}" \
                                       --bequeath \
                                       --output-format raw \
                                       --no-output-header`" || return 1

   local dependency

   set -o noglob ; IFS=$'\n'
   for header in ${headers}
   do
      IFS="${DEFAULT_IFS}"; set +o noglob

      local address
      local marks
      local include

      IFS=";" read address marks include <<< "${header}"

      if [ -z "${address}" ]
      then
         continue
      fi

      log_verbose "Emit cmake statements for ${C_MAGENTA}${C_BOLD}${address}"

      case ",${marks}," in
         *,no-dependency,*)
            emit_c_include_library "${address}" \
                                   "${marks}" \
                                   "${include}" \
                                   "$@"
         ;;

         *)
            emit_c_include_dependency "${address}" \
                                      "${marks}" \
                                      "${include}" \
                                      "$@"
         ;;
      esac
   done

   IFS="${DEFAULT_IFS}"; set +o noglob
}


output_file()
{
   log_entry "output_file" "$@"

   local filename="$1"
   local text="$2"
   local title="$3"
   local varname="$4"

   if [ "${filename}" = "-" ]
   then
      log_info "${title}"
      rexekutor printf "%s\n" "${text}"
   else
      log_verbose "Writing ${C_RESET_BOLD}${filename}"
      r_mkdir_parent_if_missing "${filename}"
      exekutor chmod a+w "${filename}"  2> /dev/null
      redirect_exekutor "${filename}" printf "%s\n" "${text}"
      exekutor chmod a-w "${filename}"  2> /dev/null
   fi
}


r_text_info_none()
{
   local key="$1"

   RVAL="/* Contents suppressed by ${key} NONE.
* Use
*   mulle-sde environment --global set ${key} DISABLE
* to not generate this file.
* Use
*   mulle-sde environment --global set MULLE_SOURCETREE_TO_C_RUN DISABLE
* to not generate any header files.
*/"
}


r_text_info_on()
{
   local key="$1"

   RVAL="/*
*   This file will be regenerated by \`mulle-sde update\` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set ${key} DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/"
}


c_include()
{
   log_entry "c_include" "$@"

   local projectname="$1"
   local projectidentifier="$2"

   local text_h

   case "${MULLE_SOURCETREE_TO_C_INCLUDE_FILE}" in
      DISABLE*)
         return
      ;;

      NONE)
         r_text_info_none 'MULLE_SOURCETREE_TO_C_INCLUDE_FILE'
         text_h="${RVAL}"
      ;;

      "")
         MULLE_SOURCETREE_TO_C_INCLUDE_FILE="${PROJECT_SOURCE_DIR}/_${projectname}-include.h"
      ;;
   esac

   if [ -z "${text_h}" ]
   then
      local marks

      case "${PROJECT_DIALECT}" in
         'objc')
            marks="no-import,public"
         ;;

         *)
            marks="public"
         ;;
      esac

      text_h="`emit_c_header "${marks}"`" || exit 1

      if [ -z "${text_h}" ]
      then
         text_h="/* no headers */"
      fi

      r_text_info_on 'MULLE_SOURCETREE_TO_C_INCLUDE_FILE'
      text_h="${RVAL}

#ifndef _${projectidentifier}_include_h__
#define _${projectidentifier}_include_h__

${text_h}

#endif"
   fi

   output_file  "${MULLE_SOURCETREE_TO_C_INCLUDE_FILE}" \
                "${text_h}" \
                "_${projectname}-include.h" \
                "MULLE_SOURCETREE_TO_C_INCLUDE_FILE"
}


objc_import()
{
   log_entry "objc_import" "$@"

   local projectname="$1"
   local projectidentifier="$2"

   local text_h

   case "${MULLE_SOURCETREE_TO_C_IMPORT_FILE}" in
      DISABLE*)
         return
      ;;

      NONE)
         r_text_info_none 'MULLE_SOURCETREE_TO_C_IMPORT_FILE'
         text_h="${RVAL}"
      ;;

      "")
         MULLE_SOURCETREE_TO_C_IMPORT_FILE="${PROJECT_SOURCE_DIR}/_${projectname}-import.h"
      ;;
   esac

   if [ -z "${text_h}" ]
   then
      text_h="`emit_c_header "import,public"`" || exit 1

      if [ -z "${text_h}" ]
      then
         text_h="/* no headers */"
      fi

      r_text_info_on 'MULLE_SOURCETREE_TO_C_IMPORT_FILE'

      #
      # if we generate an include file, we want that
      #
      case "${MULLE_SOURCETREE_TO_C_INCLUDE_FILE}" in
         DISABLE|NONE)
         ;;

         *)
            text_h="#include \"_${projectname}-include.h\"

${text_h}"
         ;;
      esac

      text_h="${RVAL}

#ifndef _${projectidentifier}_import_h__
#define _${projectidentifier}_import_h__

${text_h}

#endif"
   fi

   output_file  "${MULLE_SOURCETREE_TO_C_IMPORT_FILE}" \
                "${text_h}" \
                "_${projectname}-import.h" \
                "MULLE_SOURCETREE_TO_C_IMPORT_FILE"
}


c_include_private()
{
   log_entry "c_include_private" "$@"

   local projectname="$1"
   local projectidentifier="$2"

   local text_h

   case "${MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE}" in
      DISABLE*)
         return
      ;;

      NONE)
         r_text_info_none 'MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE'
         text_h="${RVAL}"
      ;;

      "")
         MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE="${PROJECT_SOURCE_DIR}/_${projectname}-include-private.h"
      ;;
   esac

   if [ -z "${text_h}" ]
   then
      local marks

      case "${PROJECT_DIALECT}" in
         'objc')
            marks="no-import,no-public"
         ;;

         *)
            marks="no-public"
         ;;
      esac

      text_h="`emit_c_header "${marks}"`" || exit 1

      if [ -z "${text_h}" ]
      then
         text_h="/* no headers */"
      fi

      r_text_info_on 'MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE'
      text_h="${RVAL}

#ifndef _${projectidentifier}_include_private_h__
#define _${projectidentifier}_include_private_h__

${text_h}

#endif"
   fi

   output_file "${MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE}" \
               "${text_h}" \
               "_${projectname}-include-private.h" \
               "MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE"
}


objc_import_private()
{
   log_entry "objc_import_private" "$@"

   local projectname="$1"
   local projectidentifier="$2"

   local text_h

   case "${MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE}" in
      DISABLE*)
         return
      ;;

      NONE)
         r_text_info_none 'MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE'
         text_h="${RVAL}"
      ;;


      "")
         MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE="${PROJECT_SOURCE_DIR}/_${projectname}-import-private.h"
      ;;
   esac

   if [ -z "${text_h}" ]
   then
      text_h="`emit_c_header "import,no-public"`" || exit 1

      if [ -z "${text_h}" ]
      then
         text_h="/* no headers */"
      fi

      #
      # if we generate an include file, we want that
      #
      case "${MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE}" in
         DISABLE|NONE)
         ;;

         *)
            text_h="#include \"_${projectname}-include-private.h\"

${text_h}"
         ;;
      esac

      r_text_info_on 'MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE'
      text_h="${RVAL}

#ifndef _${projectidentifier}_import_private_h__
#define _${projectidentifier}_import_private_h__

${text_h}

#endif"
   fi

   output_file "${MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE}" \
               "${text_h}" \
               "_${projectname}-import-private.h" \
               "MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE"
}


main()
{
   log_entry "main" "$@"

   # technical flags
   local MULLE_TRACE
   local MULLE_FLAG_DONT_DEFER='NO'
   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
   local MULLE_FLAG_FOLLOW_SYMLINKS='YES'
   local MULLE_FLAG_LOG_CACHE='NO'
   local MULLE_FLAG_LOG_DEBUG='NO'
   local MULLE_FLAG_LOG_EXEKUTOR='NO'
   local MULLE_FLAG_LOG_FLUFF='NO'
   local MULLE_FLAG_LOG_MERGE='NO'
   local MULLE_FLAG_LOG_SCRIPTS='NO'
   local MULLE_FLAG_LOG_SETTINGS='NO'
   local MULLE_FLAG_LOG_VERBOSE='NO'
   local MULLE_TRACE_PATHS_FLIP_X='NO'
   local MULLE_TRACE_POSTPONE='NO'
   local MULLE_TRACE_RESOLVER_FLIP_X='NO'
   local MULLE_TRACE_SETTINGS_FLIP_X='NO'

   local OPTION_IMPORT="DEFAULT"

   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            usage
         ;;

         --import)
            OPTION_IMPORT='YES'
         ;;

         --no-import)
            OPTION_IMPORT='NO'
         ;;

         -p|--project-name)
            [ "$#" -eq 1 ] && usage "Missing argument to \"$1\""
            shift

            PROJECT_NAME="$1"
         ;;

         -t|--project-type)
            [ "$#" -eq 1 ] && usage "Missing argument to \"$1\""
            shift

            PROJECT_TYPE="$1"
         ;;

         --project-source-dir)
            [ "$#" -eq 1 ] && usage "Missing argument to \"$1\""
            shift

            PROJECT_SOURCE_DIR="$1"
         ;;

         --project-dialect)
            [ "$#" -eq 1 ] && usage "Missing argument to \"$1\""
            shift

            PROJECT_DIALECT="$1"
         ;;

         --stdout)
            MULLE_SOURCETREE_TO_C_INCLUDE_FILE="-"
            MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE="-"
            MULLE_SOURCETREE_TO_C_IMPORT_FILE="-"
            MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE="-"
         ;;

         --version)
            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
            return 0
         ;;

         -*)
            log_error "Unknown option \"$1\""
            usage
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}"

   if [ -z "${MULLE_CASE_SH}" ]
   then
      # shellcheck source=mulle-case.sh
      . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-case.sh" || return 1
   fi

   if [ -z "${PROJECT_NAME}" ]
   then
   	r_fast_basename "${PWD}"
      PROJECT_NAME="${RVAL}" # could be nicer
   fi

   local PROJECT_IDENTIFIER
   local PROJECT_DOWNCASE_IDENTIFIER

   r_tweaked_de_camel_case "${PROJECT_NAME}"
   PROJECT_IDENTIFIER="${RVAL}"
   PROJECT_IDENTIFIER="`printf "%s" "${PROJECT_IDENTIFIER}" | tr -c 'a-zA-Z0-9' '_'`"
   PROJECT_DOWNCASE_IDENTIFIER="`tr 'A-Z' 'a-z' <<< "${PROJECT_IDENTIFIER}"`"

   PROJECT_SOURCE_DIR="${PROJECT_SOURCE_DIR:-.}"
   PROJECT_DIALECT="${PROJECT_DIALECT:-c}"

   c_include "${PROJECT_NAME}" "${PROJECT_DOWNCASE_IDENTIFIER}" || exit 1
   c_include_private "${PROJECT_NAME}" "${PROJECT_DOWNCASE_IDENTIFIER}" || exit 1

   if [ "${PROJECT_DIALECT}" = "objc" ]
   then
      if [ "${OPTION_IMPORT}" = "DEFAULT" ]
      then
         OPTION_IMPORT='YES'
      fi

      objc_import "${PROJECT_NAME}" "${PROJECT_DOWNCASE_IDENTIFIER}" || exit 1
      objc_import_private "${PROJECT_NAME}" "${PROJECT_DOWNCASE_IDENTIFIER}" || exit 1
   fi
}


_init()
{
   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
      [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
         echo "mulle-bashfunctions-env not installed" >&2 && \
         exit 1
   fi

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
}

_init "$@"
main "$@"

