#! /bin/sh
#
#   Copyright (c) 2022 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE:-}" = 'YES' -o "${MULLE_SOURCETREE_IMPORT_CSV_TRACE:-}" = 'YES' ] && set -x && : "$0" "$@"


SQLITE="${SQLITE:-sqlite3}"
TABLENAME="${TABLENAME:-sourcetree}"

DATABASE="${1}"
CONFIG="${2:-.mulle/etc/sourcetree/config}"
TABLENAME="${3:-sourcetree}"

[ -z "${DATABASE}" ]  && DATABASE=help
[ -z "${CONFIG}" ]    && DATABASE=help
[ -z "${TABLENAME}" ] && DATABASE=help
[ -z "${SQLITE}" ]    && DATABASE=help

case "${DATABASE}" in
   help|-h|--help)
      cat <<EOF
Usage:
   mulle-sourcetree-import-sqlite <database> [config [tablename]]]

   Read a sqlite database table and create a mulle-sourcetree config file
   from it.

   * database  : SQLITE3 database to export
   * config    : the sourcetree file to create (.mulle/etc/sourcetree/config)
   * tablename : sqlite tablename  ('sourcetree')

   The database table needs to be compatible with the CSV format produced
   by mulle-sourcetree-export-csv:

      CREATE TABLE ${TABLENAME}
      (
         address        TEXT,
         nodetype       TEXT,
         marks          TEXT,
         uuid           TEXT,
         url            TEXT,
         branch         TEXT,
         tag            TEXT,
         fetchoptions   TEXT,
         raw_userinfo   TEXT
      )

   This command needs sqlite to be installed to work.

Environment:
   SQLITE      : sqlite executable to use (${SQLITE})

EOF
      exit 1
   ;;
esac

SQLITE_EXE="`command -v "${SQLITE}" `"
[ -z "${SQLITE_EXE}" ] && echo "fatal: SQLite executable \"${SQLITE}\" is not in PATH ($PATH)" >&2 && exit 1


text="`"${SQLITE_EXE}" "${DATABASE}" \
   -cmd ".mode csv" \
   -cmd ".separator \";\"" \
   -cmd ".headers off" \
   "select address, nodetype, marks, uuid, url, branch, tag, fetchoptions, raw_userinfo
   from ${TABLENAME}"  \
| tr -d '"' \
| sed -e 's/\r$//'

`" || exit 1


dir="`dirname -- "${CONFIG}" `"

mkdir -p "${dir}" &&
printf "%s\n" "${text}" > "${CONFIG}"

