#! /usr/bin/env mulle-bash
# shellcheck shell=bash
#
#   Copyright (c) 2022 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE:-}" = 'YES' -o "${MULLE_SOURCETREE_EXPORT_JSON_TRACE:-}" = 'YES' ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION="1.1.0"

usage()
{
      cat <<EOF >&2
Usage:
   mulle-sourcetree-import-json [flags] [json]

   Read a JSON file and convert it to a mulle-sourcetree config. The incoming
   JSON must be valid and error free. The config is written to stdout unless
   a name or --write-config is specified. If <json> is ommitted or '-' stdin
   will be read.

   Needs \`jq\` installed to function.

Flags:
   --write-name <name> : name of mulle-sourcetree config to write ()
   --directory <dir>   : directory of config (.mulle/etc/sourcetree)
   --write             : shortcut for --write-name config
   --pretty            : parse pretty format (from mulle-sde dep list)

EOF
      exit 1
}


# read in one of these userinfo dicts line by line until '}'
# {
#   "aliases": "ssl",
#   "include": "openssl/ssl.h"
# }

r_read_simple_json_dict()
{
   log_entry "r_read_simple_json_dict" "$@"

   local line

   local json

   json='{'
   while read -r line
   do
      r_add_line "${json}" "${line}"
      json="${RVAL}"

      case "${line}" in
         '}')
            RVAL="${json}"
            return
         ;;
      esac
   done

   fail "malformed JSON dict: missing '}'"
}


r_parse_userinfos()
{
   log_entry "r_parse_userinfos" "$@"

   local userinfos

   local json
   local keyvalues
   local assoc_array
   local userinfo

   while read -r userinfo
   do
      case "${userinfo}" in
         '{')
            r_read_simple_json_dict
            json="${RVAL}"
            log_debug "JSON: ${json}"

            keyvalues="`rexekutor "${JQ}" -r '. | keys[] as $k ''
                                         ''| "\($k)=\(.[$k])"' <<< "${json}" `" \
                                         || exit 1


            log_debug "PARSED: ${keyvalues}"

            sourcetree::node::r_encode_userinfo "${keyvalues}"
            userinfo="${RVAL}"
         ;;

         'null')
            userinfo=""
         ;;
      esac

      log_debug "USERINFO: ${userinfo}"
      userinfo="${userinfo}"

      r_add_line_lf "${userinfos}" "${userinfo}"
      userinfos="${RVAL}"
   done

   RVAL="${userinfos}"
}


r_parse_pretty_format()
{
   log_entry "r_parse_pretty_format" "$@"

   local input="$1"

   local config
   local line key value
   local ui_line ui_key ui_value ui_info

   input="`sed 's/\x1b\[[0-9;]*m//g' <<< "${input}"`"

   local _branch
   local _address
   local _fetchoptions
   local _marks
   local _nodetype
   local _tag
   local _url
   local _raw_userinfo
   local _uuid

   while IFS= read -r line
   do
      [ -z "${line}" ] && continue

      case "${line}" in
         [[:space:]]*)
            line="${line#"${line%%[![:space:]]*}"}"

            key="${line%%:*}"
            value="${line#*:}"
            value="${value#"${value%%[![:space:]]*}"}"
            value="${value%\'}"
            value="${value#\'}"

            case "${key}" in
               branch) _branch="${value}" ;;
               fetchoptions) _fetchoptions="${value}" ;;
               marks) _marks="${value}" ;;
               nodetype) _nodetype="${value}" ;;
               tag) _tag="${value}" ;;
               url) _url="${value}" ;;
               uuid) _uuid="${value}" ;;
               userinfo)
                  ui_info=""
                  while IFS= read -r ui_line
                  do
                     ui_line="${ui_line#"${ui_line%%[![:space:]]*}"}"
                     case "${ui_line}" in
                        '}') break ;;
                        *:*)
                           ui_key="${ui_line%%:*}"
                           ui_value="${ui_line#*:}"
                           ui_value="${ui_value#"${ui_value%%[![:space:]]*}"}"
                           ui_value="${ui_value%\'}"
                           ui_value="${ui_value#\'}"
                           r_add_line "${ui_info}" "${ui_key}=${ui_value}"
                           ui_info="${RVAL}"
                        ;;
                     esac
                  done
                  _userinfo="${ui_info}"
               ;;
            esac
         ;;

         *)
            if [ ! -z "${_address}" -a ! -z "${_nodetype}" ]
            then
               sourcetree::node::r_uuidgen
               _uuid="${RVAL}"
               sourcetree::node::r_to_nodeline
               r_add_line "${config}" "${RVAL}"
               config="${RVAL}"
            fi

            _address="${line}"
            _nodetype="" _marks="" _uuid="" _url="" _branch="" _tag="" _fetchoptions="" _userinfo="" _raw_userinfo=""
         ;;
      esac
   done <<< "${input}"

   if [ ! -z "${_address}" -a ! -z "${_nodetype}" ]
   then
      sourcetree::node::r_uuidgen
      _uuid="${RVAL}"
      sourcetree::node::r_to_nodeline
      r_add_line "${config}" "${RVAL}"
      config="${RVAL}"
   fi

   RVAL="${config}"
}


main()
{
   local FLAG_NAME
   local FLAG_DIRECTORY
   local FLAG_PRETTY
   local output


   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            usage "${MULLE_TRACE}"
         ;;

         --version)
            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -d|--dir|--directory)
            [ "$#" -eq 1 ] && usage "Missing argument to \"$1\""
            shift

            FLAG_DIRECTORY="$1"
            FLAG_NAME="${FLAG_NAME:-config}"
         ;;

         --write-name)
            [ "$#" -eq 1 ] && usage "Missing argument to \"$1\""
            shift

            FLAG_DIRECTORY="${FLAG_DIRECTORY:-.mulle/etc/sourcetree}"
            FLAG_NAME="$1"
         ;;

         --write)
            FLAG_DIRECTORY="${FLAG_DIRECTORY:-.mulle/etc/sourcetree}"
            FLAG_NAME="config"
         ;;

         --pretty)
            FLAG_PRETTY='YES'
         ;;

         -*)
            log_error "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown flag \"$1\""
            usage "${MULLE_TRACE}"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   JQ="${JQ:-`command -v jq`}"
   [ -z "${JQ}" ] && fail "jq needs to be installed
${C_RESET_BOLD}   https://stedolan.github.io/jq"

   PASTE="${PASTE:-`command -v paste`}"
   [ -z "${PASTE}" ] && fail "paste, a basic unix tool, needs to be installed"


   include "array"
   include "string"
   include "sourcetree::node"

   local output

   output="-"
   if [ ! -z "${FLAG_NAME}" ]
   then
      r_filepath_concat "${FLAG_DIRECTORY}" "${FLAG_NAME}"
      output="${RVAL}"
   fi

   [ $# -gt 1 ] && shift && usage "Superfluous arguments $*"

   local config

   if [ "${FLAG_PRETTY}" = 'YES' ]
   then
      local input
      input="`rexekutor cat "$@"`"
      r_parse_pretty_format "${input}"
      config="${RVAL}"
   else
      #
      #
      #
      json="`rexekutor cat "$@"`"
      log_debug "JSON: ${json}"

      #
      # get "simple stuff"
      #
      local lines

      lines="`rexekutor "${JQ}" -r '.[]  | .address + ";" + .nodetype + ";" + .marks ''
                                            '' + ";" + .uuid     + ";" + .url ''
                                            '' + ";" + .branch   + ";" + .tag ''
                                            '' + ";" + .fetchoptions ' \
                                               <<< "${json}" `" || exit 1

      [ -z "${lines}" ] && return 0

      #
      # get userinfo
      #
      local userinfos

      local userinfo_jsons

      userinfo_jsons="`"${JQ}" '.[].userinfo' <<< "${json}" `"

      log_debug "JSON: ${userinfo_jsons}"

      r_parse_userinfos <<< "${userinfo_jsons}" || exit 1
      userinfos="${RVAL}"

      log_debug "ARRAYS: ${userinfos}"

      #
      # combine
      #

      # sed removes empty lines
      config="`"${PASTE}" -d ';' <( echo "${lines}" ) <( echo "${userinfos}" ) | sed -e '/^;$/d' `" || exit 1
   fi

   #
   #
   #
   if [ "${output}" = '-' ]
   then
      printf "%s\n" "${config}"
   else
      mkdir_parent_if_missing "${output}"
      redirect_exekutor "${output}" printf "%s\n" "${config}"
   fi
}


call_with_flags "main" "${MULLE_SOURCETREE_IMPORT_JSON_FLAGS}" "$@"
