#! /bin/sh
#
#   Copyright (c) 2022 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE:-}" = 'YES' -o "${MULLE_SOURCETREE_EDIT_TRACE:-}" = 'YES' ] && set -x && : "$0" "$@"


SQLITE="${SQLITE:-sqlite3}"
TABLENAME="sourcetree"

CONFIG="${1:-.mulle/etc/sourcetree/config}"

[ -z "${SQLITE}" ] && CONFIG=help
[ -z "${CONFIG}" ] && CONFIG=help


case "${CONFIG}" in
   help|-h|--help)
      cat <<EOF >&2
Usage:
   mulle-sourcetree-edit-csv [config]

   Edit a copy of the mulle-sourcetree config file with the spreadsheet editor
   installed on this system (that can handle CSV files).

   * config  : the sourcetree file (.mulle/etc/sourcetree/config)

   Save the edited file and run \`mulle-sourcetree-import-csv\` on it to affect
   the config file changes.

   This command needs sqlite to be installed to work.

Environment:
   SQLITE    : sqlite executable to use (${SQLITE})

EOF
      exit 1
   ;;
esac

SQLITE_EXE="`command -v "${SQLITE}" `"
[ -z "${SQLITE_EXE}" ] && echo "fatal: SQLite executable \"${SQLITE}\" is not in PATH ($PATH)" >&2 && exit 1


"${SQLITE_EXE}" ":memory:" \
   -cmd ".mode csv" \
   -cmd ".separator \";\"" \
   -cmd ".headers on" \
   -cmd "CREATE TABLE ${TABLENAME}
(
   address        TEXT,
   nodetype       TEXT,
   marks          TEXT,
   uuid           TEXT,
   url            TEXT,
   branch         TEXT,
   tag            TEXT,
   fetchoptions   TEXT,
   raw_userinfo   TEXT
)" \
   -cmd ".import \"${CONFIG}\" ${TABLENAME}" \
   -cmd ".excel" \
   "select * from ${TABLENAME}"

