#! /usr/bin/env bash

[ "${TRACE}" = "YES" ] && set -x


main()
{
   _options_mini_main "$@"

   local _marks

   nodemarks_contain_build     "${_marks}" || fail "Did expect build as default"
   nodemarks_contain_recurse   "${_marks}" || fail "Did expect recurse as default"
   nodemarks_contain_delete    "${_marks}" || fail "Did expect delete as default"
   nodemarks_contain_require   "${_marks}" || fail "Did expect require as default"
   nodemarks_contain_update    "${_marks}" || fail "Did expect update as default"

   log_verbose "----- #1 PASSED -----"

   nodemarks_contain_nobuild    "${_marks}" && fail "Did not expect nobuild as default"
   nodemarks_contain_nodelete   "${_marks}" && fail "Did not expect nodelete as default"
   nodemarks_contain_norecurse  "${_marks}" && fail "Did not expect norecurse as default"
   nodemarks_contain_norequire  "${_marks}" && fail "Did not expect norequire as default"
   nodemarks_contain_noupdate   "${_marks}" && fail "Did not expect noupdate as default"

   log_verbose "----- #2 PASSED -----"

   _marks="`nodemarks_add_nobuild "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" || fail "Did expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" && fail "Did not expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" && fail "Did not expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" && fail "Did not expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" && fail "Did not expect noupdate ($_marks)"

   log_verbose "----- #3 PASSED -----"

   _marks="`nodemarks_add_nodelete "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" || fail "Did expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" || fail "Did expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" && fail "Did not expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" && fail "Did not expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" && fail "Did not expect noupdate ($_marks)"

   log_verbose "----- #4 PASSED -----"

   _marks="`nodemarks_add_norecurse "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" || fail "Did expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" || fail "Did expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" || fail "Did expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" && fail "Did not expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" && fail "Did not expect noupdate ($_marks)"

   log_verbose "----- #5 PASSED -----"

   _marks="`nodemarks_add_norequire "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" || fail "Did expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" || fail "Did expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" || fail "Did expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" || fail "Did expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" && fail "Did not expect noupdate ($_marks)"

   log_verbose "----- #6 PASSED -----"

   _marks="`nodemarks_add_noupdate "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" || fail "Did expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" || fail "Did expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" || fail "Did expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" || fail "Did expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" || fail "Did expect noupdate ($_marks)"

   log_verbose "----- #7 PASSED -----"

# remove stuff

   _marks="`nodemarks_add_build "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" && fail "Did not expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" || fail "Did expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" || fail "Did expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" || fail "Did expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" || fail "Did expect noupdate ($_marks)"

   log_verbose "----- #8 PASSED -----"

   _marks="`nodemarks_remove "${_marks}" "nodelete"`"

   nodemarks_contain_nobuild    "${_marks}" && fail "Did not expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" && fail "Did not expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" || fail "Did expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" || fail "Did expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" || fail "Did expect noupdate ($_marks)"

   log_verbose "----- #9 PASSED -----"

   _marks="`nodemarks_remove_norecurse "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" && fail "Did not expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" && fail "Did not expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" && fail "Did not expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" || fail "Did expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" || fail "Did expect noupdate ($_marks)"

   log_verbose "----- #10 PASSED -----"

   _marks="`nodemarks_add_require "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" && fail "Did not expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" && fail "Did not expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" && fail "Did not expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" && fail "Did not expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" || fail "Did expect noupdate ($_marks)"

   log_verbose "----- #11 PASSED -----"

   _marks="`nodemarks_add_update "${_marks}"`"

   nodemarks_contain_nobuild    "${_marks}" && fail "Did not expect nobuild ($_marks)"
   nodemarks_contain_nodelete   "${_marks}" && fail "Did not expect nodelete ($_marks)"
   nodemarks_contain_norecurse  "${_marks}" && fail "Did not expect norecurse ($_marks)"
   nodemarks_contain_norequire  "${_marks}" && fail "Did not expect norequire ($_marks)"
   nodemarks_contain_noupdate   "${_marks}" && fail "Did not expect noupdate ($_marks)"

   log_verbose "----- #12 PASSED -----"

   local other

   _marks="`nodemarks_add_noupdate "${_marks}"`"
   other="`nodemarks_add_nodelete "${_marks}"`"

   nodemarks_intersect "${_marks}" "${other}" || fail "intersect \"${_marks}\" \"${other}\""

   log_verbose "----- #13 PASSED -----"

   other="`nodemarks_add_nodelete ""`"

   nodemarks_intersect "${_marks}" "${other}" && fail "! intersect \"${_marks}\" \"${other}\""

   log_verbose "----- #14 PASSED -----"

   log_info "----- ALL PASSED -----"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env library-path`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
}


init "$@"
main "$@"
