#! /usr/bin/env bash


run_test_1()
{
   local nodeline

   nodeline="_address;_nodetype;_marks;_uuid;_url;_branch;_tag;_fetchoptions;_userinfo"

   local _branch
   local _address
   local _fetchoptions
   local name
   local _nodetype
   local _marks
   local _tag
   local _url
   local _userinfo
   local _uuid

   nodeline_parse "${nodeline}"

   [ "${_address}"      = "_address" ]      || fail "wrong _address \"${_address}\""
   [ "${_url}"          = "_url" ]          || fail "wrong name \"${_url}\""
   [ "${_branch}"       = "_branch" ]       || fail "wrong _branch \"${_branch}\""
   [ "${_tag}"          = "_tag" ]          || fail "wrong _tag \"${_tag}\""
   [ "${_nodetype}"     = "_nodetype" ]     || fail "wrong _nodetype \"${_nodetype}\""
   [ "${_marks}"        = "_marks" ]        || fail "wrong _marks \"${_marks}\""
   [ "${_fetchoptions}" = "_fetchoptions" ] || fail "wrong _nodetype \"${_fetchoptions}\""
   [ "${_userinfo}"     = "_userinfo" ]     || fail "wrong _userinfo \"${_userinfo}\""
   [ "${_uuid}"         = "_uuid" ]         || fail "wrong _uuid \"${_uuid}\""

   local printed

   printed="`node_print_nodeline "${nodeline}"`"

   [ "${nodeline}" = "${printed}" ]     || fail "printed nodeline differs \"${printed}\""
}


run_test_2()
{
   local _branch
   local _address
   local _fetchoptions
   local name
   local _nodetype
   local _marks
   local _tag
   local _url
   local _userinfo

   nodeline_parse "whatever;xyz;;_uuid-required;abc"

   [ "${_url}"     = "abc" ]          || fail "wrong name \"${_url}\""
   [ "${_address}" = "whatever" ]     || fail "wrong _address \"${_address}\""
   [ -z "${_branch}"       ]          || fail "wrong _branch \"${_branch}\""
   [ -z "${_tag}"          ]          || fail "wrong _tag \"${_tag}\""
   [ "${_nodetype}" = "xyz"  ]        || fail "wrong _nodetype \"${_nodetype}\""
   [ -z "${_marks}"        ]          || fail "wrong _marks \"${_marks}\""
   [ -z "${_fetchoptions}" ]          || fail "wrong _nodetype \"${_fetchoptions}\""
   [ -z "${_userinfo}"     ]          || fail "wrong _userinfo \"${_userinfo}\""
   [ "${_uuid}" = "_uuid-required" ]   || fail "wrong _uuid \"${_uuid}\""
}



main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@"

   set -e # for tests

   run_test_1
   log_verbose "----- #1 PASSED -----"

   run_test_2
   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env library-path`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
}


init "$@"
main "$@"

