#! /usr/bin/env zsh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


expect()
{
   local output="$1"
   local expected="$2"

   if [ "${output}" != "${expected}" ]
   then
      internal_fail "Did expect \"${expected}\" but got \"${output}\""
   fi
}


run_mulle_sourcetree()
{
   log_fluff "${C_MAGENTA}${C_BOLD}####################################"
   log_fluff "${C_MAGENTA}${C_BOLD}${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} $*"
   log_fluff "${C_MAGENTA}${C_BOLD}####################################"

   exekutor ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} "$@"
}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@"

   set -e

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   cd "${directory}"
   r_physicalpath "${directory}"
   MULLE_VIRTUAL_ROOT="${RVAL}"

   mkdir_if_missing "${directory}/a"
   mkdir_if_missing "${directory}/a/b"

   cd "${directory}"

   if [ -f ".mulle/etc/sourcetree/config" ]
   then
      internal_fail "config should not exist"
   fi

   if ! run_mulle_sourcetree -N add --marks "no-delete,no-update,no-share" "a"
   then
      internal_fail "add internal_failed unexpectedly"
   fi

   if run_mulle_sourcetree -N add --marks "no-delete,no-update,no-share" "a"
   then
      internal_fail "duplicate add succeeded unexpectedly"
   fi

   if run_mulle_sourcetree -N add --marks "no-delete,no-update,no-share" "."
   then
      internal_fail "add \".\" succeeded unexpectedly"
   fi

   if run_mulle_sourcetree -N add --marks "no-delete,no-update,no-share" -s local "/"
   then
      internal_fail "/ add succeeded unexpectedly"
   fi

   if ! [ -f ".mulle/etc/sourcetree/config" ]
   then
      internal_fail "config should exist now"
   fi

   if ! run_mulle_sourcetree -N add --marks "no-delete,no-update,no-share" "b"
   then
      internal_fail "add of b internal_failed unexpectedly"
   fi

   if ! run_mulle_sourcetree -N remove "a"
   then
      internal_fail "remove \"a\" internal_failed unexpectedly"
   fi

   if run_mulle_sourcetree -N remove "a"
   then
      internal_fail "superflous remove \"a\" succeeded unexpectedly"
   fi

   if run_mulle_sourcetree -N remove "."
   then
      internal_fail "remove \".\" succeeded unexpectedly"
   fi

   if [ ! -f ".mulle/etc/sourcetree/config" ]
   then
      internal_fail "config should still exist now"
   fi

   if ! run_mulle_sourcetree -N remove "b"
   then
      internal_fail "remove \"a\" internal_failed unexpectedly"
   fi

   # this has changes, the sourcetree stays to clobber share
   if [ ! -f ".mulle/etc/sourcetree/config" ]
   then
      internal_fail "config should still exist"
   fi

   log_verbose "----- #1 PASSED -----"

   #
   # add a git url
   #
   if ! run_mulle_sourcetree -N add "https://a.com/a.git"
   then
      internal_fail "add URL, internal_failed unexpectedly"
   fi

   log_verbose "Informational output"
   run_mulle_sourcetree -N list

   local address="`run_mulle_sourcetree -N get a address`"
   local nodetype="`run_mulle_sourcetree -N get a nodetype`"
   local url="`run_mulle_sourcetree -N get a url`"

   if [ "${nodetype}" != "git" ] || [ "${address}" != "a" ] || [ "${url}" != "https://a.com/a.git" ]
   then
      internal_fail "#1 did not work (${address};${nodetype};${url})"
   fi

   if ! run_mulle_sourcetree -N add -u "https://a.com/a.git" b
   then
      internal_fail "add URL, internal_failed unexpectedly"
   fi

   log_verbose "Informational output"
   run_mulle_sourcetree -N list

   local address="`run_mulle_sourcetree -N get b address`"
   local nodetype="`run_mulle_sourcetree -N get b nodetype`"
   local url="`run_mulle_sourcetree -N get b url`"

   if [ "${nodetype}" != "git" ] || [ "${address}" != "b" ] || [ "${url}" != "https://a.com/a.git" ]
   then
      internal_fail "#2 did not work (${address};${nodetype};${url})"
   fi

   log_verbose "----- #2 PASSED -----"

   if ! run_mulle_sourcetree -N add --nodetype symlink --url "/a.com/a" c
   then
      internal_fail "add URL, internal_failed unexpectedly"
   fi

   log_verbose "Informational output"
   run_mulle_sourcetree -N list

   local address="`run_mulle_sourcetree -N get c address`"
   local nodetype="`run_mulle_sourcetree -N get c nodetype`"
   local url="`run_mulle_sourcetree -N get c url`"

   if [ "${nodetype}" != "symlink" ] || [ "${address}" != "c" ] || [ "${url}" != "/a.com/a" ]
   then
      internal_fail "#3 did not work (${address};${nodetype};${url})"
   fi

   log_verbose "----- #3 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
}


init "$@"
main "$@"

