#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###

expect()
{
   local output="$1"
   local expected="$2"

   if [ "${output}" != "${expected}" ]
   then
      _internal_fail "Did expect \"${expected}\" but got \"${output}\""
   fi
}


run_mulle_sourcetree()
{
   log_fluff "${C_MAGENTA}${C_BOLD}####################################"
   log_fluff "${C_MAGENTA}${C_BOLD}${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS:-} $*"
   log_fluff "${C_MAGENTA}${C_BOLD}####################################"

   exekutor ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS:-} "$@"
}


test_run()
{
   if ! run_mulle_sourcetree -N add --marks "no-delete,no-update,no-share" "a"
   then
      _internal_fail "add failed unexpectedly"
   fi

   if run_mulle_sourcetree --no-errors -s -N add --marks "no-delete,no-update,no-share" "a"
   then
      _internal_fail "duplicate add succeeded unexpectedly"
   fi

   if run_mulle_sourcetree --no-errors -s -N add --marks "no-delete,no-update,no-share" "."
   then
      _internal_fail "add \".\" succeeded unexpectedly"
   fi

   if run_mulle_sourcetree --no-errors -s -N add --marks "no-delete,no-update,no-share" -s local "/"
   then
      _internal_fail "/ add succeeded unexpectedly"
   fi

   if ! [ -f ".mulle/etc/sourcetree/config" ]
   then
      _internal_fail "config should exist now"
   fi

   if ! run_mulle_sourcetree -s -N add --marks "no-delete,no-update,no-share" "b"
   then
      _internal_fail "add of b failed unexpectedly"
   fi

   if ! run_mulle_sourcetree -N remove "a"
   then
      _internal_fail "remove \"a\" failed unexpectedly"
   fi

   if run_mulle_sourcetree --no-errors -s -N remove "a"
   then
      _internal_fail "superflous remove \"a\" succeeded unexpectedly"
   fi

   if run_mulle_sourcetree --no-errors -s -N remove "."
   then
      _internal_fail "remove \".\" succeeded unexpectedly"
   fi

   if [ ! -f ".mulle/etc/sourcetree/config" ]
   then
      _internal_fail "config still exist now"
   fi
}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   set -e

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   cd "${directory}"
   r_physicalpath "${directory}"
   MULLE_VIRTUAL_ROOT="${RVAL}"

   mkdir_if_missing "${directory}/a"
   mkdir_if_missing "${directory}/a/b"

   cd "${directory}"

   if [ -f ".mulle/etc/sourcetree/config" ]
   then
      _internal_fail "#1.1 config should not exist"
   fi

   test_run

   if ! run_mulle_sourcetree -N remove "b"
   then
      _internal_fail "remove \"b\" failed unexpectedly"
   fi

   # there is no fallback, the sourcetree should be gone
   if [ -d ".mulle/etc/sourcetree" ]
   then
      tree -a .mulle >&2
      _internal_fail "#1.2 config should not exist now"
   fi

   log_verbose "----- #1 PASSED -----"

   test_run

   # create a bogus fallback sourcetree, do it now after test_run otherwise
   # mulle-sourcettree will still clobber it, because as soon as
   # contents are identical, it's superflous

   mkdir_if_missing ".mulle/share/sourcetree"
   redirect_exekutor ".mulle/share/sourcetree/config" echo "ignore;comment"

   if ! run_mulle_sourcetree -N remove "b"
   then
      _internal_fail "remove \"b\" failed unexpectedly"
   fi

   # this has changes, the sourcetree stays to clobber share
   if [ ! -f ".mulle/etc/sourcetree/config" ]
   then
      _internal_fail "#2.1 config should exist now"
   fi

   rmdir_safer ".mulle/share/sourcetree"

   log_verbose "----- #2 PASSED -----"

   mkdir_if_missing ".mulle/share/sourcetree"
#  redirect_exekutor ".mulle/share/sourcetree/config" echo "ignore;comment" 

   test_run

   if ! run_mulle_sourcetree -N remove "b"
   then
      _internal_fail "remove \"b\" failed unexpectedly"
   fi

   if [ -f ".mulle/etc/sourcetree/config" ]
   then
      _internal_fail "#3.1 config should not exist now"
   fi

   rmdir_safer ".mulle/share/sourcetree"

   log_verbose "----- #3 PASSED -----"


   #
   # add a git url
   #
   if ! run_mulle_sourcetree -s -N add "https://a.com/a.git"
   then
      _internal_fail "add URL, failed unexpectedly"
   fi

   log_verbose "Informational output"
   run_mulle_sourcetree -N list

   local address="`run_mulle_sourcetree -N get a address`"
   local nodetype="`run_mulle_sourcetree -N get a nodetype`"
   local url="`run_mulle_sourcetree -N get a url`"

   if [ "${nodetype}" != "git" ] || [ "${address}" != "a" ] || [ "${url}" != "https://a.com/a.git" ]
   then
      _internal_fail "#4.1 did not work (${address};${nodetype};${url})"
   fi

   if ! run_mulle_sourcetree -N add -u "https://a.com/a.git" b
   then
      _internal_fail "add URL, failed unexpectedly"
   fi

   log_verbose "Informational output"
   run_mulle_sourcetree -N list

   local address="`run_mulle_sourcetree -N get b address`"
   local nodetype="`run_mulle_sourcetree -N get b nodetype`"
   local url="`run_mulle_sourcetree -N get b url`"

   if [ "${nodetype}" != "git" ] || [ "${address}" != "b" ] || [ "${url}" != "https://a.com/a.git" ]
   then
      _internal_fail "#4.2 did not work (${address};${nodetype};${url})"
   fi

   log_verbose "----- #4 PASSED -----"

   if ! run_mulle_sourcetree -s -N add --nodetype symlink --url "/a.com/a" c
   then
      _internal_fail "add URL, failed unexpectedly"
   fi

   log_verbose "Informational output"
   run_mulle_sourcetree -N list

   local address="`run_mulle_sourcetree -N get c address`"
   local nodetype="`run_mulle_sourcetree -N get c nodetype`"
   local url="`run_mulle_sourcetree -N get c url`"

   if [ "${nodetype}" != "symlink" ] || [ "${address}" != "c" ] || [ "${url}" != "/a.com/a" ]
   then
      _internal_fail "#5 did not work (${address};${nodetype};${url})"
   fi

   log_verbose "----- #5 PASSED -----"

   log_info "----- ALL PASSED -----"
   cd ..
   rmdir_safer "${directory}"
}


init()
{
   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
}


init "$@"
main "$@"

