#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sourcetree()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS:-} "$@"
   log_fluff "####################################" >&2

   (
      set +e
      
      MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} libexec-dir`"

      . "${MULLE_SOURCETREE}" --no-auto-shell ${MULLE_SOURCETREE_FLAGS:-} "$@"
   )
}


#
#  a -> b
#  a -> c
#  b -> c
#
main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"


   mkdir_if_missing "${directory}"
   cd "${directory}" || exit 1

   # place a into different
   run_mulle_sourcetree --config-name "different" add a || exit 1
   if ! run_mulle_sourcetree --config-name "different" get a > /dev/null
   then
      fail "a is gone ($PWD)"
   fi
   if run_mulle_sourcetree get a > /dev/null
   then
      fail "a should not have been found ($PWD)"
   fi
   log_verbose "----- #1 PASSED -----"

   # place b into config (default)
   run_mulle_sourcetree add b || exit 1

   # should not be found, as different supersedes config
   if run_mulle_sourcetree --config-name "different:config" get b > /dev/null
   then
      fail "b was found, though it shouldn't have been ($PWD)"
   fi

   if ! run_mulle_sourcetree --config-name "config" get b > /dev/null
   then
      fail "b should have been found ($PWD)"
   fi

   log_verbose "----- #2 PASSED -----"


   log_info "----- ALL PASSED -----"

   # rmdir_safer "${directory}"
}


init()
{
   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh"     || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh"       || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-callback.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-sync.sh"     || exit 1
}


init "$@"
main "$@"

