#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


main()
{
   _options_mini_main "$@" && set -x

   local _marks

   # absent version mark matches everything
   unset GLOBAL_FOO 

   sourcetree::nodemarks::filter_with_qualifier "${_marks}" "IFDEF GLOBAL_FOO"      && internal_fail "Undefined GLOBAL_FOO should not match"
   sourcetree::nodemarks::filter_with_qualifier "${_marks}" "NOT IFDEF GLOBAL_FOO"  || internal_fail "Undefined GLOBAL_FOO should not match"

   log_verbose "----- #1 PASSED -----"


   GLOBAL_FOO="whatever"
   export GLOBAL_FOO

   sourcetree::nodemarks::filter_with_qualifier "${_marks}" "IFDEF GLOBAL_FOO"   || internal_fail "Defined GLOBAL_FOO should match"
   sourcetree::nodemarks::filter_with_qualifier "${_marks}" "NOT IFDEF GLOBAL_FOO" && internal_fail "Defined GLOBAL_FOO should match"

   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"
}



init()
{
   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodemarks.sh" || exit 1
}


init "$@"
main "$@"
