#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


expect_actions()
{
   local actions="$1"
   local expected="$2"

   actions="$(sort <<< "${actions}")"

   expected="$(tr ',' '\012' <<< "${expected}")"
   expected="$(sort <<< "${expected}")"

   if [ "${actions}" != "${expected}" ]
   then
      log_error "Unexpected output generated"
      cat <<EOF >&2
----------------
Output:
----------------
${actions}
----------------
Expected:
----------------
${expected}
----------------
EOF
      exit 1
   fi
}



run_git_tests()
{
   local old
   local new

   local uuid
   local uuid2

   r_node_uuidgen
   uuid="${RVAL}"

   old="ringo/starr;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"

   # into empty is simple
   new="paul/jones;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "fetch"
   log_verbose "----- #1 PASSED -----"

   r_node_uuidgen
   uuid2="${RVAL}"

   # uuid change is bug
   new="ringo/starr;git;;;${uuid2};https://github.com/mulle-nat/mulle-c11.git;release"
   ( update_actions_for_nodelines "${old}" "${new}" ) 2> /dev/null && fail "did not fail unexpectedly"
   log_verbose "----- #2 PASSED -----"

   mkdir_if_missing "ringo"
   exekutor touch "ringo/starr"

   # _url change for git is supported
   new="ringo/starr;git;;${uuid};https://github.com/mulle-objc/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "set-url,upgrade"

   log_verbose "----- #3 PASSED -----"

   # _branch change for git is supported
   new="ringo/starr;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;master"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "checkout"

   log_verbose "----- #4 PASSED -----"

   # _tag change needs a checkout
   new="ringo/starr;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release;frobozz"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "checkout"

   log_verbose "----- #5 PASSED -----"

   # let it move the _address around
   new="paul/jones;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "move"

   log_verbose "----- #6 PASSED -----"

   # let it do nothing if we moved
   mkdir_if_missing "paul"
   exekutor touch "paul/jones"
   rmdir_safer "ringo"

   new="paul/jones;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "remember"

   log_verbose "----- #7 PASSED -----"


   old="paul/jones;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"

   # lets change _url and dst at the same time
   new="tom/petty;git;;${uuid};https://github.com/mulle-objc/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "move,upgrade,set-url"

   log_verbose "----- #8 PASSED -----"

   # change of _nodetype is heavy _url and dst at the same time
   new="paul/jones;svn;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "fetch,remove"

   log_verbose "----- #9 PASSED -----"

   # change in marks,fetchoptions,userinfo = don't care
   new="paul/jones;git;no-build;${uuid};https://github.com/mulle-nat/mulle-c11.git;release;;fetch=whatever;_userinfo"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" ""

   log_verbose "----- #10 PASSED -----"
}



run_tar_tests()
{
   local uuid
   local old
   local new

   r_node_uuidgen
   uuid="${RVAL}"

   # into empty is simple
   new="ringo/starr;tar;;${uuid};https://github.com/mulle-nat/mulle-c11/archive/1.2.5.tar.gz"
   actions="`update_actions_for_nodelines "normal" "" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "fetch"
   log_verbose "----- #11 PASSED -----"

   old="ringo/starr;tar;;${uuid};https://github.com/mulle-nat/mulle-c11/archive/1.2.5.tar.gz"

   mkdir_if_missing "ringo"
   exekutor touch "ringo/starr"

   # _url change means refetch
   new="ringo/starr;tar;;${uuid};https://github.com/mulle-nat/mulle-c11/archive/1.2.7.tar.gz"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "fetch,remove"

   log_verbose "----- #12 PASSED -----"

   # let it move the dstination around
   new="paul/jones;tar;;${uuid};https://github.com/mulle-nat/mulle-c11/archive/1.2.5.tar.gz"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "move"

   log_verbose "----- #13 PASSED -----"
}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   set -e

   directory="`make_tmp_directory`" || exit 1
   MULLE_VIRTUAL_ROOT="`physicalpath "${directory}"`"
   export MULLE_VIRTUAL_ROOT

   (
      cd "${directory}" &&
      run_git_tests
   ) || exit 1
   rmdir_safer "${directory}"

   directory="`make_tmp_directory`" || exit 1
   (
      cd "${directory}" &&
      run_tar_tests
   ) || exit 1
   rmdir_safer "${directory}"

   log_info "----- ALL PASSED -----"

}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-action.sh" || exit 1
}


init "$@"
main "$@"

