#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


expect_actions()
{
   local actions="$1"
   local expected="$2"

   actions="$(sort <<< "${actions}")"

   expected="$(tr ',' '\012' <<< "${expected}")"
   expected="$(sort <<< "${expected}")"

   if [ "${actions}" != "${expected}" ]
   then
      log_error "Unexpected output generated"
      cat <<EOF >&2
----------------
Result:
----------------
${actions}
----------------
Expected:
----------------
${expected}
----------------
EOF
      exit 1
   fi
}



update_actions_for_nodelines()
{
   log_entry "update_actions_for_nodelines" "$@"

   [ "$#" -ne 3  ] && _internal_fail "api error"

   local style="$1"
   local previousnodeline="$2"
   local nodeline="$3"

   [ -z "${style}" ]   && _internal_fail "style is empty"
   [ -z "${nodeline}" ] && _internal_fail "nodeline is empty"

   local _branch
   local _address
   local _fetchoptions
   local _marks
   local _nodetype
   local _tag
   local _url
   local _raw_userinfo
   local _userinfo
   local _uuid

   sourcetree::nodeline::parse "${nodeline}" # !!

   local previousfilename
   local filename

   filename="${_address}"
   sourcetree::nodeline::r_get_address "${previousnodeline}"
   previousfilename="${RVAL}"

   # just _address as filename ?
   sourcetree::action::r_update_actions_for_node "${style}" \
                                                 "${nodeline}" \
                                                 "${filename}" \
                                                 "${previousnodeline}" \
                                                 "${previousfilename}" \
                                                 "/" \
                                                 "/" \
                                                 \
                                                 "${_address}" \
                                                 "${_nodetype}" \
                                                 "${_marks}" \
                                                 "${_uuid}" \
                                                 "${_url}" \
                                                 "${_branch}" \
                                                 "${_tag}"
   echo "${RVAL}"
}


run_git_tests()
{
   local old
   local new

   local uuid
   local uuid2

   sourcetree::node::r_uuidgen
   uuid="${RVAL}"

   old="ringo/starr;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"

   # into empty is simple
   new="paul/jones;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "fetch"
   log_verbose "----- #1 PASSED -----"

   sourcetree::node::r_uuidgen
   uuid2="${RVAL}"

   # uuid change is bug
   new="ringo/starr;git;;;${uuid2};https://github.com/mulle-nat/mulle-c11.git;release"
   ( update_actions_for_nodelines "${old}" "${new}" ) 2> /dev/null && fail "did not fail unexpectedly"
   log_verbose "----- #2 PASSED -----"

   mkdir_if_missing "ringo"
   exekutor touch "ringo/starr"

   # _url change for git is supported
   new="ringo/starr;git;;${uuid};https://github.com/mulle-objc/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "set-url,upgrade"

   log_verbose "----- #3 PASSED -----"

   # _branch change for git is supported
   new="ringo/starr;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;master"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "checkout"

   log_verbose "----- #4 PASSED -----"

   # _tag change needs a checkout
   new="ringo/starr;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release;frobozz"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "checkout"

   log_verbose "----- #5 PASSED -----"

   # let it move the _address around
   new="paul/jones;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "move"

   log_verbose "----- #6 PASSED -----"

   # let it do nothing if we moved
   mkdir_if_missing "paul"
   exekutor touch "paul/jones"
   rmdir_safer "ringo"

   new="paul/jones;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "remember"

   log_verbose "----- #7 PASSED -----"


   old="paul/jones;git;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"

   # lets change _url and dst at the same time
   new="tom/petty;git;;${uuid};https://github.com/mulle-objc/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "move,upgrade,set-url"

   log_verbose "----- #8 PASSED -----"

   # change of _nodetype is heavy _url and dst at the same time
   new="paul/jones;svn;;${uuid};https://github.com/mulle-nat/mulle-c11.git;release"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "fetch,remove"

   log_verbose "----- #9 PASSED -----"

   # change in marks,fetchoptions,userinfo = don't care
   new="paul/jones;git;no-build;${uuid};https://github.com/mulle-nat/mulle-c11.git;release;;fetch=whatever;_userinfo"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" ""

   log_verbose "----- #10 PASSED -----"
}



run_tar_tests()
{
   local uuid
   local old
   local new

   sourcetree::node::r_uuidgen
   uuid="${RVAL}"

   # into empty is simple
   new="ringo/starr;tar;;${uuid};https://github.com/mulle-nat/mulle-c11/archive/1.2.5.tar.gz"
   actions="`update_actions_for_nodelines "normal" "" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "fetch"
   log_verbose "----- #11 PASSED -----"

   old="ringo/starr;tar;;${uuid};https://github.com/mulle-nat/mulle-c11/archive/1.2.5.tar.gz"

   mkdir_if_missing "ringo"
   exekutor touch "ringo/starr"

   # _url change means refetch
   new="ringo/starr;tar;;${uuid};https://github.com/mulle-nat/mulle-c11/archive/1.2.7.tar.gz"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "fetch,remove"

   log_verbose "----- #12 PASSED -----"

   # let it move the dstination around
   new="paul/jones;tar;;${uuid};https://github.com/mulle-nat/mulle-c11/archive/1.2.5.tar.gz"
   actions="`update_actions_for_nodelines "normal" "${old}" "${new}"`" || fail "failed unexpectedly"
   expect_actions "${actions}" "move"

   log_verbose "----- #13 PASSED -----"
}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   set -e

   r_make_tmp_directory || exit 1
   directory="${RVAL}"

   r_physicalpath "${directory}"
   MULLE_VIRTUAL_ROOT="${RVAL}"

   (
      cd "${directory}" &&
      run_git_tests
   ) || exit 1

   rmdir_safer "${directory}"

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   (
      cd "${directory}" &&
      run_tar_tests
   ) || exit 1

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"

}


init()
{
   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-action.sh" || exit 1
}


init "$@"
main "$@"

