#! /usr/bin/env zsh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


expect()
{
   local output="$1"
   local expected="$2"

   if [ "${output}" != "${expected}" ]
   then
      exekutor fail "Did expect \"${expected}\" but got \"${output}\""
   fi
}


_setup_demo_repo_a()
{
   exekutor git init

   exekutor git checkout -b release

   redirect_exekutor VERSION echo "1.0.0"
   exekutor git add VERSION
   exekutor git commit -m "a: 1.0.0"
   exekutor git tag "1.0.0"

   redirect_exekutor VERSION echo "2.0.0"
   exekutor git commit -m "a: 2.0.0" VERSION
   exekutor git tag "2.0.0"
}


setup_demo_repos()
{
   local repos="$1"
   (
      set -e
      mkdir_if_missing "${repos}/a" &&
      exekutor cd "${repos}/a" && _setup_demo_repo_a
   )
}


run_test()
{
   local uuidgen

   _uuid="`uuidgen`"
   (
      do_actions_with_nodeline "ringo/starr;git;;${_uuid};${repos}/a;release" "flat" "/" "/"
   ) || fail "failed unexpectedly"

   [ -f "ringo/starr/VERSION" ] || fail "ringo/starr/VERSION not there ($PWD)"
   log_verbose "----- #1 PASSED -----"

   (
      do_actions_with_nodeline "ringo/star;git;;${_uuid};${repos}/a;release" "flat" "/" "/"
   ) || fail "failed unexpectedly"

   [ -f "ringo/starr/VERSION" ] && fail "ringo/starr/VERSION not gone ($PWD)"
   [ -f "ringo/star/VERSION" ]  || fail "ringo/star/VERSION not there ($PWD)"
   log_verbose "----- #2 PASSED -----"

   (
      do_actions_with_nodeline "ringo/starr;git;;${_uuid};${repos}/a;not_there" "flat" "/" "/"
   ) && fail "worked unexpectedly"

   [ -f "ringo/star/VERSION" ]    && fail "branch not_there should have wiped ringo/star/VERSION"
   log_verbose "----- #3 PASSED -----"

   (
      do_actions_with_nodeline "ringo/starr;git;;${_uuid};${repos}/a;release;2.0.0" "flat" "/" "/"
   ) || fail "failed unexpectedly"

   [ `cat ringo/starr/VERSION` = 2.0.0 ] || fail "Wrong checkout"

   log_verbose "----- #4 PASSED -----"

   (
      do_actions_with_nodeline "ringo/starr;git;;${_uuid};${repos}/a;release;1.0.0" "flat" "/" "/"
   ) || fail "failed unexpectedly"

   [ `cat ringo/starr/VERSION` = 1.0.0 ] || fail "Wrong checkout"

   log_verbose "----- #5 PASSED -----"
}



main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   local SOURCETREE_FIX_FILENAME=".mulle-sourcetree.fix"

   local project
   local repos

   project="${directory}/project"
   repos="${directory}/repositories"

   setup_demo_repos "${repos}"

   mkdir_if_missing "${project}"

   MULLE_VIRTUAL_ROOT="`physicalpath "${directory}/project"`"
   export MULLE_VIRTUAL_ROOT

   (
      SOURCETREE_DB_FILENAME="db"
      SOURCETREE_DB_FILENAME_RELATIVE=".."

      cd "${project}" &&
      run_test
   ) || exit 1

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh"     || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodemarks.sh"     || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-cfg.sh"      || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh"       || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-action.sh"   || exit 1
}


init "$@"
main "$@"

