#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sourcetree()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS:-} "$@"
   log_fluff "####################################" >&2

   (
      set +e
      
      MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} libexec-dir`"

      . "${MULLE_SOURCETREE}" ${MULLE_SOURCETREE_FLAGS:-} "$@"
   )
}

#
# repository has no .mulle in 1.0.0
# repository has a .mulle in 2.0.0
# repository has no .mulle in 3.0.0
#
_setup_demo_repo_a()
{
   local reporoot="$1"

   exekutor git init --initial-branch=master

   redirect_exekutor VERSION echo "1.0.0"
   run_mulle_sourcetree add --nodetype git "file://${reporoot}/b"
   run_mulle_sourcetree -s add --nodetype git --url "file://${reporoot}/d" "c/d"
   exekutor git add VERSION .mulle
   exekutor git commit -m "a: initial version"
}

_setup_demo_repo_b()
{
   local reporoot="$1"

   exekutor git init --initial-branch=master

   redirect_exekutor VERSION echo "1.1.0"
   run_mulle_sourcetree add --nodetype git "file://${reporoot}/d"
   exekutor git add VERSION .mulle
   exekutor git commit -m "b: initial version"
}


_setup_demo_repo_d()
{
   local reporoot="$1"

   exekutor git init --initial-branch=master

   redirect_exekutor VERSION echo "1.0.0"
   exekutor git add VERSION
   exekutor git commit -m "d: initial version"
}


setup_demo_repos()
{
   (
      set -e
      mkdir_if_missing "$1/a" &&
      exekutor cd "$1/a" && _setup_demo_repo_a "$1"
      mkdir_if_missing "$1/b" &&
      exekutor cd "$1/b" && _setup_demo_repo_b "$1"
      mkdir_if_missing "$1/d" &&
      exekutor cd "$1/d" && _setup_demo_repo_d "$1"
      set +e
   ) || exit 1
}


run_test1()
{
   local repos="$1"

   if ! run_mulle_sourcetree add --nodetype git --url "file://${repos}/a" "root/a"
   then
      _internal_fail "add failed unexpectedly"
   fi
   log_verbose "----- #1 PASSED -----"

   if run_mulle_sourcetree fix
   then
      _internal_fail "fix worked unexpectedly"
   fi
   log_info "Failed as expected"
   log_verbose "----- #2 PASSED -----"

   if ! run_mulle_sourcetree --recurse update  # > /dev/null 2>&1
   then
      _internal_fail "update failed unexpectedly"
   fi
   log_verbose "----- #3 PASSED -----"

   # now move directory b away

   mv root/a/b root/

   local result
   local expected

   if ! result="`run_mulle_sourcetree fix`"
   then
      _internal_fail "fix failed unexpectedly"
   fi

   expected="mulle-sourcetree set url root/b"
   case "${result}" in
      *set*root/b*)
      ;;

      *)
         _internal_fail "got \"${result}\""
      ;;
   esac
   log_verbose "----- #4 PASSED -----"

   mkdir -p foo/x
   mv root/b foo/x/

   if ! result="`run_mulle_sourcetree fix`"
   then
      _internal_fail "fix failed unexpectedly"
   fi

   case "${result}" in
      *set*foo/x*)
      ;;

      *)
         _internal_fail "got \"${result}\""
      ;;
   esac
   log_verbose "----- #5 PASSED -----"

   rm -rf foo/x/

   if ! result="`run_mulle_sourcetree fix`"
   then
      _internal_fail "fix failed unexpectedly"
   fi

   case "${result}" in
      *remove*b\'*)
      ;;

      *)
         _internal_fail "got \"${result}\" ($PWD)"
      ;;
   esac
   log_verbose "----- #6 PASSED -----"
}



main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   local project

   project="${directory}/project"
   repos="${directory}/repositories"

   setup_demo_repos "${repos}" > /dev/null 2>&1 || exit 1

   (
      rmdir_safer "${project}" &&
      mkdir_if_missing "${project}" &&

      r_physicalpath "${project}"
      MULLE_VIRTUAL_ROOT="${RVAL}"
      export MULLE_VIRTUAL_ROOT

      cd "${project}" &&
      run_test1 "${repos}"
   ) || exit 1

   log_info "----- ALL PASSED -----"
   cd ..
   rmdir_safer "${directory}"
}


init()
{
   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh"     || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh"      || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh"    || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-dotdump.sh" || exit 1
}


init "$@"
main "$@"

