#! /usr/bin/env bash

[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"


run_mulle_sourcetree()
{
   log_fluff "####################################"
   log_fluff ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} "$@"
}


_setup_demo_repo_a()
{
   local reporoot="$1"

   exekutor git init

   exekutor git checkout -b release

   redirect_exekutor VERSION echo "1.0.0"
   exekutor git add VERSION
   exekutor git commit -m "a: 1.0.0"
   exekutor git tag "1.0.0"

   redirect_exekutor VERSION echo "2.0.0"
   exekutor git commit -m "a: 2.0.0" VERSION
   exekutor git tag "2.0.0"

#   exekutor git branch -d master
}


setup_demo_repos()
{
   (
      set -e
      mkdir_if_missing "$1/a" &&
      exekutor cd "$1/a" && _setup_demo_repo_a "$1"
      set +e
   )
}


test_bad_paths()
{
   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "/tmp/foo"
   then
      internal_fail "internal_failed to complain about absolute path"
   fi
   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "a: .mulle-sourcetree/etc/config should not exist"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "a: .mulle-sourcetree/var/db should not exist"

   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "../foo"
   then
      internal_fail "internal_failed to complain about escape path"
   fi
   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "b: .mulle-sourcetree/etc/config should not exist"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "b: .mulle-sourcetree/var/db should not exist"

   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "a/../.."
   then
      internal_fail "internal_failed to complain about escape path"
   fi
   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "c: .mulle-sourcetree/etc/config should not exist"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "c: .mulle-sourcetree/var/db should not exist"

   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "~foo"
   then
      internal_fail "internal_failed to complain about absolute path"
   fi
   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "d: .mulle-sourcetree/etc/config should not exist"
   [ -e ".mulle-sourcetree/var/db" ]    && internal_fail "d: .mulle-sourcetree/var/db should not exist"

   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "~/foo"
   then
      internal_fail "internal_failed to complain about absolute path"
   fi
   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "e: .mulle-sourcetree/etc/config should not exist"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "e: .mulle-sourcetree/var/db should not exist"

   :
}


test_simple_add_remove()
{
   if ! run_mulle_sourcetree add --nodetype git --branch release --url "${repos}/a" "foo"
   then
      internal_fail "internal_failed unexpectedly"
   fi
   [ -f ".mulle-sourcetree/etc/config" ] || internal_fail "a: .mulle-sourcetree/etc/config should exist now"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "a: .mulle-sourcetree/var/db should not exist"

   # same _url should not work
   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "foo"
   then
      internal_fail "succeeded unexpectedly"
   fi
   [ -f ".mulle-sourcetree/etc/config" ] || internal_fail "b: .mulle-sourcetree/etc/config should exist now"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "b: .mulle-sourcetree/var/db should not exist"

   if ! run_mulle_sourcetree remove "foo"
   then
      internal_fail "internal_failed unexpectedly"
   fi
   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "c: .mulle-sourcetree/etc/config should not exist anymore"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "c: .mulle-sourcetree/var/db should not exist"

   :
}


test_update1()
{
   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "a: .mulle-sourcetree/etc/config should not exist anymore"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "a: .mulle-sourcetree/var/db should not exist"
   [ -e "foo" ]                      && internal_fail "a: foo should not exist"

   if ! run_mulle_sourcetree add --nodetype git --branch release --url "${repos}/a" "foo"
   then
      internal_fail "add internal_failed unexpectedly"
   fi

   [ -e ".mulle-sourcetree/etc/config" ] || internal_fail "b: .mulle-sourcetree should now exist"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "b: .mulle-sourcetree/var/db should not exist"
   [ -e "foo" ]                      && internal_fail "b: foo should not exist"

   if ! run_mulle_sourcetree update
   then
      internal_fail "update internal_failed unexpectedly"
   fi

   [ -e ".mulle-sourcetree/etc/config" ] || internal_fail "c: .mulle-sourcetree/etc/config should exist"
   [ -e ".mulle-sourcetree/var/db" ]     || internal_fail "c: .mulle-sourcetree/var/db should exist"
   [ -f "foo/VERSION" ]              || internal_fail "c: foo/VERSION should exist"

   if ! run_mulle_sourcetree remove "foo"
   then
      internal_fail "remove internal_failed unexpectedly"
   fi

   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "d: .mulle-sourcetree/etc/config should not exist anymore"
   [ -e ".mulle-sourcetree/var/db" ]     || internal_fail "d: .mulle-sourcetree/var/db should exist"
   [ -f "foo/VERSION" ]              || internal_fail "d: foo/VERSION should exist"

   if ! run_mulle_sourcetree update
   then
      internal_fail "update internal_failed unexpectedly"
   fi

   [ -e ".mulle-sourcetree/etc/config" ]    && internal_fail "e: .mulle-sourcetree/etc/config should not exist anymore"
   [ -e "foo" ]                         && internal_fail "e: foo should not exist"
   [ -e ".mulle-sourcetree/var/db" ]        || internal_fail "e: .mulle-sourcetree/var/db should exist"
   [ -e ".mulle-sourcetree/var/graveyard" ] || internal_fail "e: .mulle-sourcetree/var/graveyard should exist"

   :
}


test_update2()
{
   rm -rf foo 2> /dev/null
   rm -rf .mulle-sourcetree/var/db 2> /dev/null
   rm -f .mulle-sourcetree 2> /dev/null

   [ -e ".mulle-sourcetree/etc/config" ] && internal_fail "a: .mulle-sourcetree/etc/config should not exist anymore"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "a: .mulle-sourcetree/var/db should not exist"
   [ -e "foo" ]                      && internal_fail "a: foo should not exist"

   if ! run_mulle_sourcetree add --nodetype git --branch release --url "${repos}/a" "foo"
   then
      internal_fail "add internal_failed unexpectedly"
   fi

   [ -e ".mulle-sourcetree/etc/config" ] || internal_fail "b: .mulle-sourcetree should now exist"
   [ -e ".mulle-sourcetree/var/db" ]     && internal_fail "b: .mulle-sourcetree/var/db should not exist"
   [ -e "foo" ]                      && internal_fail "b: foo should not exist"

   if ! run_mulle_sourcetree update
   then
      internal_fail "update internal_failed unexpectedly"
   fi

   [ -e ".mulle-sourcetree/etc/config" ] || internal_fail "c: .mulle-sourcetree/etc/config should exist"
   [ -e ".mulle-sourcetree/var/db" ]     || internal_fail "c: .mulle-sourcetree/var/db should exist"
   [ -f "foo/VERSION" ]              || internal_fail "c: foo/VERSION should exist"

   if ! run_mulle_sourcetree set --address "bar" foo
   then
      internal_fail "set internal_failed unexpectedly"
   fi

   [ -e ".mulle-sourcetree/etc/config" ] || internal_fail "d: .mulle-sourcetree/etc/config should exist"
   [ -e ".mulle-sourcetree/var/db" ]     || internal_fail "d: .mulle-sourcetree/var/db should exist"
   [ -f "foo/VERSION" ]              || internal_fail "d: foo/VERSION should exist"
   [ -f "bar/VERSION" ]              && internal_fail "d: bar/VERSION should not exist"

   if ! run_mulle_sourcetree update
   then
      internal_fail "update internal_failed unexpectedly"
   fi

   [ -e ".mulle-sourcetree/etc/config" ] || internal_fail "e: .mulle-sourcetree/etc/config should exist"
   [ -e ".mulle-sourcetree/var/db" ]     || internal_fail "e: .mulle-sourcetree/var/db should exist"
   [ -f "foo/VERSION" ]              && internal_fail "e: foo/VERSION should exist"
   [ -f "bar/VERSION" ]              || internal_fail "e: bar/VERSION should exist"

   :
}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   directory="`make_tmp_directory`" || exit 1
   MULLE_VIRTUAL_ROOT="${directory}"
   export MULLE_VIRTUAL_ROOT

   SOURCETREE_DB_NAME=".mulle-sourcetree/var/db"
   export SOURCETREE_DB_NAME

   local project
   local repos

   project="${directory}/project"
   repos="${directory}/repositories"

   setup_demo_repos "${repos}"

   mkdir_if_missing "${project}"
   (
      cd "${project}"

      test_bad_paths &&
      log_verbose "----- #1 PASSED -----"
   ) || exit 1

   (
      cd "${project}"

      test_simple_add_remove &&
      log_verbose "----- #2 PASSED -----"
   ) || exit 1

   (
      cd "${project}"

      test_update1 &&
      log_verbose "----- #3 PASSED -----"
   ) || exit 1

   (
      cd "${project}"

      test_update2 &&
      log_verbose "----- #4 PASSED -----"
   ) || exit 1

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-update.sh" || exit 1
}


init "$@"
main "$@"

