#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


run_mulle_sourcetree()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SOURCETREE} ${MULLE_SOURCETREE_FLAGS} "$@"
   log_fluff "####################################" >&2

   (
      MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} libexec-dir`"

      . "${MULLE_SOURCETREE}" --no-auto-shell ${MULLE_SOURCETREE_FLAGS} "$@"
   )
}
#
# repository has no .mulle in 1.0.0
# repository has a .mulle in 2.0.0
# repository has no .mulle in 3.0.0
#
_setup_demo_repo_a()
{
   local reporoot="$1"

   exekutor git init

   redirect_exekutor VERSION echo "1.0.0"
   run_mulle_sourcetree add --nodetype git "file://${reporoot}/b"
   run_mulle_sourcetree add --nodetype git "file://${reporoot}/c"
   exekutor git add VERSION .mulle
   exekutor git commit -m "a: initial version"
}

_setup_demo_repo_b()
{
   local reporoot="$1"

   exekutor git init

   redirect_exekutor VERSION echo "1.1.0"
   run_mulle_sourcetree add --nodetype git "file://${reporoot}/c"
   exekutor git add VERSION .mulle
   exekutor git commit -m "b: initial version"
}


_setup_demo_repo_c()
{
   local reporoot="$1"

   exekutor git init

   redirect_exekutor VERSION echo "1.0.0"
   exekutor git add VERSION
   exekutor git commit -m "c: initial version"
}



_change_demo_repo_a()
{
   local reporoot="$1"

   run_mulle_sourcetree mark "b" "no-share"
   exekutor git commit -m "a: no-share version" .mulle
}


change_demo_repo_a_set_b_to_noshare()
{
   (
      exekutor cd "$1/a" && _change_demo_repo_a "$1"
   ) || exit 1
}

setup_demo_repos()
{
   (
      set -e
      mkdir_if_missing "$1/a" &&
      exekutor cd "$1/a" && _setup_demo_repo_a "$1"
      mkdir_if_missing "$1/b" &&
      exekutor cd "$1/b" && _setup_demo_repo_b "$1"
      mkdir_if_missing "$1/c" &&
      exekutor cd "$1/c" && _setup_demo_repo_c "$1"
      set +e
   ) || exit 1
}


run_test1()
{
   if ! run_mulle_sourcetree add --nodetype git "file://${repos}/a"
   then
      fail "add failed unexpectedly"
   fi
   if ! run_mulle_sourcetree add --nodetype git "file://${repos}/b"
   then
      fail "add failed unexpectedly"
   fi
   if ! MULLE_SOURCETREE_STASH_DIRNAME="shared" run_mulle_sourcetree --share update
   then
      fail "update failed unexpectedly"
   fi

   [ -d "shared/a" ] || fail "1: shared/a should exist"
   [ -d "shared/b" ] || fail "1: shared/b should exist"
   [ -d "shared/c" ] || fail "1: shared/c should exist"
}


run_test2()
{
   if ! run_mulle_sourcetree add --nodetype git "file://${repos}/a"
   then
      fail "add failed unexpectedly"
   fi

   if ! MULLE_SOURCETREE_STASH_DIRNAME="shared" run_mulle_sourcetree --share update
   then
      fail "update failed unexpectedly"
   fi

   [ -d "shared/a" ] || fail "2: shared/a should exist"
   [ -d "shared/b" ] || fail "2: shared/b should exist"
   [ -d "shared/c" ] || fail "2: shared/c should exist"
}


run_test3()
{
   local flags="$1"

   if ! run_mulle_sourcetree add --nodetype git "file://${repos}/a"
   then
      fail "add failed unexpectedly"
   fi

   run_mulle_sourcetree list

   MULLE_SOURCETREE_STASH_DIRNAME="shared"
   export MULLE_SOURCETREE_STASH_DIRNAME

   if ! run_mulle_sourcetree ${flags} --share update
   then
      fail "update failed unexpectedly"
   fi

   if [ -z ${flags} ]
   then
      [ -d "${MULLE_SOURCETREE_STASH_DIRNAME}/a" ]   || fail "3: ${MULLE_SOURCETREE_STASH_DIRNAME}/a should exist"
      [ -d "${MULLE_SOURCETREE_STASH_DIRNAME}/b" ]   && fail "3: ${MULLE_SOURCETREE_STASH_DIRNAME}/b should not exist"
      [ -d "${MULLE_SOURCETREE_STASH_DIRNAME}/c" ]   || fail "3: ${MULLE_SOURCETREE_STASH_DIRNAME}/c should exist"

      [ -d "${MULLE_SOURCETREE_STASH_DIRNAME}/a/b" ] || fail "3: ${MULLE_SOURCETREE_STASH_DIRNAME}/a/b should exist"

      # this is debatable i don't know
      # [ -d "shared/a/b/c" ] || fail "shared/a/b/c should exist"
   fi
   MULLE_SOURCETREE_STASH_DIRNAME=
}


#
# test absolute MULLE_SOURCETREE_STASH_DIR
#
run_test4()
{
   local directory="$1"

   if ! run_mulle_sourcetree add --nodetype git "file://${repos}/a"
   then
      fail "add failed unexpectedly"
   fi

   run_mulle_sourcetree list

   MULLE_SOURCETREE_STASH_DIR="${directory}/shared_global"
   export MULLE_SOURCETREE_STASH_DIR

   if ! run_mulle_sourcetree --share update
   then
      fail "update failed unexpectedly"
   fi

   [ -d "${MULLE_SOURCETREE_STASH_DIR}/a" ]   || fail "4: ${MULLE_SOURCETREE_STASH_DIR}/a should exist"
   [ -d "${MULLE_SOURCETREE_STASH_DIR}/b" ]   && fail "4: ${MULLE_SOURCETREE_STASH_DIR}/b should not exist"
   [ -d "${MULLE_SOURCETREE_STASH_DIR}/c" ]   || fail "4: ${MULLE_SOURCETREE_STASH_DIR}/c should exist"

   [ -d "${MULLE_SOURCETREE_STASH_DIR}/a/b" ] || fail "4: ${MULLE_SOURCETREE_STASH_DIR}/a/b should exist"

      # this is debatable i don't know
      # [ -d "shared/a/b/c" ] || fail "shared/a/b/c should exist"
   MULLE_SOURCETREE_STASH_DIR=
}


main()
{
   MULLE_SOURCETREE_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   local project

   project="${directory}/project"
   repos="${directory}/repositories"

   mkdir_if_missing "${project}"

   setup_demo_repos "${repos}"

#   (
#      rmdir_safer "${project}" &&
#      mkdir_if_missing "${project}" &&
#      cd "${project}" &&
#      run_test1
#   ) || exit 1
#   log_verbose "----- #1 PASSED -----"
#
#   (
#      rmdir_safer "${project}" &&
#      mkdir_if_missing "${project}" &&
#      cd "${project}" &&
#      run_test2
#   ) || exit 1
#   log_verbose "----- #2 PASSED -----"
#
#   #
#   #
#   #

   change_demo_repo_a_set_b_to_noshare "${repos}"
#
#   (
#      rmdir_safer "${project}" &&
#      mkdir_if_missing "${project}" &&
#      cd "${project}" &&
#      run_test3
#   ) || exit 1
#   log_verbose "----- #3 PASSED -----"
#
   (
      rmdir_safer "${project}" &&
      mkdir_if_missing "${project}" &&
      cd "${project}" &&
      run_test4 "${directory}"
   ) || exit 1
   log_verbose "----- #4 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
   MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1

   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh"     || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh"       || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-callback.sh" || exit 1
   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-sync.sh"     || exit 1
}


init "$@"
main "$@"

